import AboutDescription from "../../components/AboutDescription/AboutDescription";
import Banner from "../../components/Banner/Banner";
import Team from "../../components/Team/Team";
import Head from "next/dist/shared/lib/head";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import Navigation from "../../components/Navigation/Navigation";
import useIsMobile from "../../hooks/useIsMobile";

export default function About(): JSX.Element {
  const bannerHeading = "Строительная компания «ЯраМарк»",
    bannerText =
      "Наша компания основана 20 января 2020 года и действует по настоящее время, юридический и почтовый адрес: 223053, Минский район, д. Боровляны, улица Березовая роща, 21";

  const { isMobile, getIsMobile, onCloseMobileMenu } = useIsMobile();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isMobile={isMobile} getIsMobile={getIsMobile} />

      <Navigation isMobile={isMobile} onClose={onCloseMobileMenu} />
      <main className="main">
        <Banner heading={bannerHeading} text={bannerText} />

        <AboutDescription />

        <Team />
      </main>

      <Footer />
    </>
  );
}
