import Head from "../node_modules/next/head";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Navigation from "../components/Navigation/Navigation";
import PreviewModal from "../components/PreviewModal/PreviewModal";
import Preview from "../components/Preview/Preview";
import About from "../components/About/About";
import Services from "../components/Services/Services";
import CompanyObjects from "../components/CompanyObjects/CompanyObjects";
import Reviews from "../components/Reviews/Reviews";
import { useCallback, useState } from "react";
import { ObjectCarouselModel } from "../models/models";
import useIsMobile from "../hooks/useIsMobile";

export default function Home(): JSX.Element {
  let [isOpenPreview, setIsOpenPreview] = useState(false);
  let [selectSrc, setSelectSrc] = useState("");
  let [selectWEBPSrc, setSelectWEBPSrc] = useState("");
  let [selectAlt, setSelectAlt] = useState("");
  const { isMobile, getIsMobile, onCloseMobileMenu } = useIsMobile();

  const onClose = useCallback(() => {
    setIsOpenPreview(false);
    setSelectSrc("");
    setSelectWEBPSrc("");
    setSelectAlt("");
  }, []);

  const openPreview = useCallback((preview: ObjectCarouselModel) => {
    setSelectSrc(preview.src);
    setSelectWEBPSrc(preview.WEBPsrc || "");
    setSelectAlt(preview.alt);
    setIsOpenPreview(true);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isMobile={isMobile} getIsMobile={getIsMobile} />

      <Navigation isMobile={isMobile} onClose={onCloseMobileMenu} />

      {isOpenPreview && (
        <PreviewModal
          onClose={onClose}
          previewSrc={selectSrc}
          previewWEBPSrc={selectWEBPSrc}
          previewAlt={selectAlt}
        />
      )}

      <main className="main">
        <Preview />

        <About />

        <Services />

        <CompanyObjects />

        <Reviews openPreview={openPreview} />
      </main>

      <Footer />
    </>
  );
}
