import Email from '../../assets/svg/Email';
import Phone from '../../assets/svg/Phone';
import Location from '../../assets/svg/Location';

import Head from '../../node_modules/next/dist/shared/lib/head';
import Header from '../../components/Header/Header';
import Footer from '../../components/Footer/Footer';
import Navigation from '../../components/Navigation/Navigation';
import useIsMobile from "../../hooks/useIsMobile";
import classes from './ContactsPage.module.css';

export default function Contacts(): JSX.Element {
  const { isMobile, getIsMobile, onCloseMobileMenu } = useIsMobile();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Header isMobile={isMobile} getIsMobile={getIsMobile} />

  <Navigation isMobile={isMobile} onClose={onCloseMobileMenu} />
        <main className="main">
        <section className={classes.contacts}>
        <div className={classes.contactsDescrition}>
            <h1 className={classes.contactsDescritionHeading}>ООО «ЯраМарк»</h1>

            <ul className={`${classes.contactsDescritionList} ${classes.contactsDescritionListBg}`}>
                <li className={classes.contactsDescritionListItem}>
                    <Location fill={'#FFCB00'} />

                    <p>223053, Минский район, д. Боровляны, улица Березовая роща, 21</p>
                </li>

                <li className={`${classes.contactsDescritionListItem} ${classes.telephones}`}>
                    <Phone fill={'#FFCB00'} />

                    <a className={classes.mobile} href="tel:+375445725497">+375 44 572-54-97</a>
                    <a className={classes.tel} href="tel:+375175120755">+375 17 512-07-55</a>
                </li>

                <li className={classes.contactsDescritionListItem}>
                    <Email fill={'#FFCB00'} />

                    <a href="mailto:yaramark@mail.ru">yaramark@mail.ru</a>
                </li>
            </ul>
        </div>

        <div className={classes.contactsMap}>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2345.059553079556!2d27.6753051!3d54.001718499999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbc85c15a3626b%3A0xcb86bd0eb9c4017f!2sUlitsa%20Berozovaya%20Roshcha%2021%2C%20Barauliany%20223053!5e0!3m2!1sen!2sby!4v1659353118768!5m2!1sen!2sby" width="auto" height="700" allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </section>
        </main>

<Footer />
    </>
  )
};
